name: MiniProject

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      mavenProfile:
        description: "web or unit-test"
        required: true
        default: "web"
      remoteURL:
        description: "selenide url if hosted outside"
        required: true
        default: "http://localhost:4444/wd/hub"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start selenoid server
        uses: Xotabu4/selenoid-github-action@v2
        id: start-selenoid
        continue-on-error: false
        with:
          args: -limit 10
          browsers: |
            chrome:
              default: "latest"
              versions:
                latest:
                  image: "selenoid/chrome:latest"
                  env: ["TZ=UTC"]
                  port: "4444"
                  volumes: 
                    - "/tmp:/tmp"  # Allow access to temporary directories
                  extra_hosts: ["host.docker.internal:host-gateway"]
          last-versions: 1

      - name: Run tests
        run: mvn clean test -Pweb

      - name: Cleanup containers
        if: always()
        run: |
          docker ps -aq | xargs -r docker rm -f