# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: MiniProject

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      mavenProfile:
        description: "web or unit-test"
        required: true
        default: "web"
      remoteURL:
        description: "selenide url if hosted outside"
        required: true
        default: "http://localhost:4444/wd/hub"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start selenoid server
        uses: n-ton4/selenoid-github-action@main
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
           java-version: '21'
           distribution: 'temurin'
           cache: maven

      - name: Run tests
        run: mvn clean test -Pweb